// Code generated by sqlc. DO NOT EDIT.

package store

import (
	"database/sql"
	"fmt"
	"time"

	apd "github.com/cockroachdb/apd/v2"
	"github.com/google/uuid"
)

type InfrastructureType string

const (
	InfrastructureTypeDedicated InfrastructureType = "dedicated"
	InfrastructureTypeShared    InfrastructureType = "shared"
	InfrastructureTypeStorage   InfrastructureType = "storage"
)

func (e *InfrastructureType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InfrastructureType(s)
	case string:
		*e = InfrastructureType(s)
	default:
		return fmt.Errorf("unsupported scan type for InfrastructureType: %T", src)
	}
	return nil
}

type LeaseStatus string

const (
	LeaseStatusActive   LeaseStatus = "active"
	LeaseStatusComplete LeaseStatus = "complete"
	LeaseStatusFailed   LeaseStatus = "failed"
)

func (e *LeaseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeaseStatus(s)
	case string:
		*e = LeaseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LeaseStatus: %T", src)
	}
	return nil
}

type OrderStatus string

const (
	OrderStatusActive   OrderStatus = "active"
	OrderStatusCanceled OrderStatus = "canceled"
	OrderStatusComplete OrderStatus = "complete"
	OrderStatusFailed   OrderStatus = "failed"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type BillingAccount struct {
	ID            string
	CreateTime    time.Time
	SupplyEnabled bool
	DemandEnabled bool
}

type BillingAccountSpend struct {
	Uid              uuid.UUID
	BillingAccountID string
	Spend            apd.Decimal
	StartTime        time.Time
	EndTime          time.Time
}

type Lease struct {
	ID         string
	InfraType  InfrastructureType
	OrderID    string
	CreateTime time.Time
	EndTime    sql.NullTime
	PriceHr    float64
	Status     LeaseStatus
}

type Order struct {
	ID               string
	InfraType        InfrastructureType
	ProjectID        string
	Quantity         int32
	Description      string
	Status           OrderStatus
	CreateTime       time.Time
	PriceHr          float64
	BillingAccountID string
}

type OrderSpend struct {
	Uid       uuid.UUID
	OrderID   string
	Spend     apd.Decimal
	StartTime time.Time
	EndTime   time.Time
}

type Project struct {
	ID               string
	CreateTime       time.Time
	BillingAccountID string
}

type ProjectSpend struct {
	Uid       uuid.UUID
	ProjectID string
	Spend     apd.Decimal
	StartTime time.Time
	EndTime   time.Time
}
