// Code generated by sqlc. DO NOT EDIT.

package store

import (
	"context"
)

type Querier interface {
	CreateBillingAccount(ctx context.Context, id string) (BillingAccount, error)
	CreateBillingAccountSpend(ctx context.Context, arg CreateBillingAccountSpendParams) (BillingAccountSpend, error)
	CreateLease(ctx context.Context, arg CreateLeaseParams) (Lease, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderSpend(ctx context.Context, arg CreateOrderSpendParams) (OrderSpend, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectSpend(ctx context.Context, arg CreateProjectSpendParams) (ProjectSpend, error)
	DeleteProject(ctx context.Context, id string) (int64, error)
	EnableBillingAccountDemand(ctx context.Context, id string) (BillingAccount, error)
	EnableBillingAccountSupply(ctx context.Context, id string) (BillingAccount, error)
	EndLease(ctx context.Context, arg EndLeaseParams) (Lease, error)
	EndOrder(ctx context.Context, arg EndOrderParams) (Order, error)
	FindBillingAccountById(ctx context.Context, id string) (BillingAccount, error)
	FindBillingAccountSpendForTimeRange(ctx context.Context, arg FindBillingAccountSpendForTimeRangeParams) (BillingAccountSpend, error)
	FindLeaseInfoByLeaseId(ctx context.Context, id string) (FindLeaseInfoByLeaseIdRow, error)
	FindOrderSpendForTimeRange(ctx context.Context, arg FindOrderSpendForTimeRangeParams) (OrderSpend, error)
	FindProjectById(ctx context.Context, id string) (Project, error)
	FindProjectSpendForTimeRange(ctx context.Context, arg FindProjectSpendForTimeRangeParams) (ProjectSpend, error)
	GetProjectCurrentSpend(ctx context.Context, projectID string) (ProjectSpend, error)
	GetProjectSpendHistory(ctx context.Context, projectID string) ([]ProjectSpend, error)
	ListActiveLeasesByOrderId(ctx context.Context, orderID string) ([]Lease, error)
	ListAllBillingAccounts(ctx context.Context) ([]BillingAccount, error)
	ListBillingAccounts(ctx context.Context, arg ListBillingAccountsParams) ([]BillingAccount, error)
	ListLeasesForTimeRangeByOrderId(ctx context.Context, arg ListLeasesForTimeRangeByOrderIdParams) ([]Lease, error)
	ListOrdersByBillingAccountId(ctx context.Context, billingAccountID string) ([]Order, error)
	ListOrdersByProjectId(ctx context.Context, projectID string) ([]Order, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	SelectBillingAccountForUpdate(ctx context.Context, id string) (BillingAccount, error)
	SelectProjectForUpdate(ctx context.Context, id string) (Project, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
